chore: remove redundant `.as_ref()`
This fixes:
```
error[E0282]: type annotations needed
  --> core/store/src/migrations.rs:65:30
   |
65 |         let entry_size = key.as_ref().len() + value_bytes.len() + 8;
   |                              ^^^^^^   --- type must be known at this point
   |
help: try using a fully qualified path to specify the expected types
   |
65 -         let entry_size = key.as_ref().len() + value_bytes.len() + 8;
65 +         let entry_size = <[u8] as AsRef<T>>::as_ref(key).len() + value_bytes.len() + 8;
   |

For more information about this error, try `rustc --explain E0282`.
error: could not compile `near-store` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
```

```
error[E0277]: the trait bound `[u8]: std::convert::AsRef<[{integer}; 8]>` is not satisfied
   --> tools/cold-store/src/cli.rs:660:49
    |
660 |         let cold_state_key = [&[1; 8], trie_key.as_ref()].concat();
    |                                                 ^^^^^^ the trait `std::convert::AsRef<[{integer}; 8]>` is not implemented for `[u8]`
    |
    = help: the following other types implement trait `std::convert::AsRef<T>`:
              `[u8]` implements `std::convert::AsRef<winnow::stream::bstr::BStr>`
              `[u8]` implements `std::convert::AsRef<winnow::stream::bytes::Bytes>`

error[E0599]: the method `concat` exists for array `[&[{integer}; 8]; 2]`, but its trait bounds were not satisfied
   --> tools/cold-store/src/cli.rs:660:59
    |
660 |         let cold_state_key = [&[1; 8], trie_key.as_ref()].concat();
    |                                                           ^^^^^^
    |
    = note: the following trait bounds were not satisfied:
            `[&[{integer}; 8]]: std::slice::Concat<_>`

Some errors have detailed explanations: E0277, E0599.
For more information about an error, try `rustc --explain E0277`.
```

Which was triggered by tweaking Wasmtime feature flags

Signed-off-by: Roman Volosatovs <roman@cosmonic.com>